In [1]:
import numpy as np

In [2]:
mm = np.array([[.023,.427,.55],[.005,.002,.993],[.213,.272,.515]])
mm

array([[ 0.023,  0.427,  0.55 ],
       [ 0.005,  0.002,  0.993],
       [ 0.213,  0.272,  0.515]])

In [35]:
mm@mm@mm@mm@mm@mm@mm@mm@mm@mm@mm@mm@mm@mm

array([[ 0.13859956,  0.23108892,  0.63031152],
       [ 0.13859959,  0.23108891,  0.6303115 ],
       [ 0.13859958,  0.23108893,  0.63031148]])

In [32]:
mmn = mm;
for x in range(0,5-1):
    mmn = mm@mmn
mmn

array([[ 0.140221  ,  0.23044326,  0.62933575],
       [ 0.13853316,  0.23269711,  0.62876973],
       [ 0.1382674 ,  0.2306413 ,  0.6310913 ]])

In [33]:
np.linalg.matrix_power(mm,5)

array([[ 0.140221  ,  0.23044326,  0.62933575],
       [ 0.13853316,  0.23269711,  0.62876973],
       [ 0.1382674 ,  0.2306413 ,  0.6310913 ]])

In [34]:
from numpy.linalg import inv

In [87]:
from numpy.linalg import eig
evals, evecs = eig(mm)
evals

array([ 1.00+0.j        , -0.23+0.17504285j, -0.23-0.17504285j])

In [23]:
evecs

array([[ 0.57735027+0.j        ,  0.70223358+0.j        ,  0.70223358-0.j        ],
       [ 0.57735027+0.j        , -0.41151479+0.54545384j,
        -0.41151479-0.54545384j],
       [ 0.57735027+0.j        , -0.00354233-0.19997786j,
        -0.00354233+0.19997786j]])

In [98]:
evecs[0]/np.real(evecs[0,0]+evecs[0,1]+evecs[0,2])@mm

array([ 0.08394617+0.j,  0.22148386+0.j,  0.69456998+0.j])

In [85]:
site = 0;
hits = np.zeros((3));
for x in range(0,100000):
    site = np.random.choice(np.array([0,1,2]),p=mm[site])
    hits[site] += 1
hits/100000.

array([ 0.13748,  0.2318 ,  0.63072])