In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_table('u.data',sep='\t',names=['user','item','rating','time'])
df1b = pd.read_table('u1.base',sep='\t',names=['user','item','rating','time'])
df1t = pd.read_table('u1.test',sep='\t',names=['user','item','rating','time'])

In [4]:
df1b

user  item  rating       time
0         1     1       5  874965758
1         1     2       3  876893171
2         1     3       4  878542960
3         1     4       3  876893119
4         1     5       3  889751712
...     ...   ...     ...        ...
79995   943  1067       2  875501756
79996   943  1074       4  888640250
79997   943  1188       3  888640250
79998   943  1228       3  888640275
79999   943  1330       3  888692465

[80000 rows x 4 columns]

In [5]:
[max(df['user']),
max(df['item']),
max(df['rating'])]

[943, 1682, 5]

In [6]:
ui = np.zeros((max(df['user']),max(df['item'])))
for i in range(943):
    user_i = df1b[df1b.user == i+1]
    for j in user_i.item:
        ui[i,j-1] = user_i[user_i.item == j].rating.tolist()[0]

In [7]:
ui

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [30]:
uu = np.corrcoef(ui)
uu

array([[ 1.        ,  0.05987607,  0.02164287, ...,  0.13392732,
         0.08070283,  0.18842177],
       [ 0.05987607,  1.        ,  0.03425405, ...,  0.11817385,
         0.09806701,  0.06088546],
       [ 0.02164287,  0.03425405,  1.        , ...,  0.07122259,
         0.05763835, -0.01636086],
       ...,
       [ 0.13392732,  0.11817385,  0.07122259, ...,  1.        ,
         0.08012962,  0.06529963],
       [ 0.08070283,  0.09806701,  0.05763835, ...,  0.08012962,
         1.        ,  0.12773543],
       [ 0.18842177,  0.06088546, -0.01636086, ...,  0.06529963,
         0.12773543,  1.        ]])

In [21]:
df1t

user  item  rating       time
0         1     6       5  887431973
1         1    10       3  875693118
2         1    12       5  878542960
3         1    14       5  874965706
4         1    17       3  875073198
...     ...   ...     ...        ...
19995   458   648       4  886395899
19996   458  1101       4  886397931
19997   459   934       3  879563639
19998   460    10       3  882912371
19999   462   682       5  886365231

[20000 rows x 4 columns]

In [69]:
coradf = df1b[df1b['item'] == 6]
coradf

user  item  rating       time
1460     18     6       5  880130764
4069     71     6       3  880864124
4263     76     6       5  875028165
9397    181     6       1  878962866
10478   198     6       2  884206270
34665   486     6       4  879874902
38638   524     6       5  884627388
40371   537     6       2  886029806
43828   568     6       3  877907235
45286   590     6       5  879439145
51868   655     6       4  887425812
53209   662     6       5  880571006
56765   707     6       3  886285627
61515   758     6       2  881976919
62766   773     6       3  888538620
66274   806     6       2  882385063
67683   828     6       1  891035614
71836   870     6       4  875680311
78190   924     6       4  886759441
79287   936     6       5  886832636

In [40]:
uudf = pd.DataFrame(uu[0])
uudf

0
0    1.000000
1    0.059876
2    0.021643
3   -0.002790
4    0.145655
..        ...
938  0.053361
939  0.169154
940  0.133927
941  0.080703
942  0.188422

[943 rows x 1 columns]

In [70]:
cora = pd.DataFrame.to_numpy(coradf)

In [132]:
cora[:,0]-1

array([ 17,  70,  75, 180, 197, 485, 523, 536, 567, 589, 654, 661, 706,
       757, 772, 805, 827, 869, 923, 935], dtype=int64)

In [72]:
uu[0,cora[:,0]-1]

array([0.23314291, 0.11066227, 0.16666486, 0.01806079, 0.19053804,
       0.14786297, 0.18217781, 0.23225986, 0.09542636, 0.13384753,
       0.20767433, 0.10110861, 0.14545014, 0.20249207, 0.26399841,
       0.26148366, 0.0998323 , 0.24886099, 0.16726742, 0.15232833])

In [135]:
corasim = np.transpose(np.concatenate(([cora[:,0]],[cora[:,2]],[uu[0,cora[:,0]-1]]),axis = 0))
corasim

array([[1.80000000e+01, 5.00000000e+00, 2.33142909e-01],
       [7.10000000e+01, 3.00000000e+00, 1.10662269e-01],
       [7.60000000e+01, 5.00000000e+00, 1.66664865e-01],
       [1.81000000e+02, 1.00000000e+00, 1.80607926e-02],
       [1.98000000e+02, 2.00000000e+00, 1.90538039e-01],
       [4.86000000e+02, 4.00000000e+00, 1.47862966e-01],
       [5.24000000e+02, 5.00000000e+00, 1.82177812e-01],
       [5.37000000e+02, 2.00000000e+00, 2.32259857e-01],
       [5.68000000e+02, 3.00000000e+00, 9.54263580e-02],
       [5.90000000e+02, 5.00000000e+00, 1.33847534e-01],
       [6.55000000e+02, 4.00000000e+00, 2.07674331e-01],
       [6.62000000e+02, 5.00000000e+00, 1.01108609e-01],
       [7.07000000e+02, 3.00000000e+00, 1.45450139e-01],
       [7.58000000e+02, 2.00000000e+00, 2.02492069e-01],
       [7.73000000e+02, 3.00000000e+00, 2.63998408e-01],
       [8.06000000e+02, 2.00000000e+00, 2.61483663e-01],
       [8.28000000e+02, 1.00000000e+00, 9.98323013e-02],
       [8.70000000e+02, 4.00000

In [136]:
np.shape(corasim)

(20, 3)

In [137]:
corasimsort = np.sort(corasim,axis = 0)
corasimsort = corasimsort[::-1]
corasimsort

array([[9.36000000e+02, 5.00000000e+00, 2.63998408e-01],
       [9.24000000e+02, 5.00000000e+00, 2.61483663e-01],
       [8.70000000e+02, 5.00000000e+00, 2.48860989e-01],
       [8.28000000e+02, 5.00000000e+00, 2.33142909e-01],
       [8.06000000e+02, 5.00000000e+00, 2.32259857e-01],
       [7.73000000e+02, 5.00000000e+00, 2.07674331e-01],
       [7.58000000e+02, 4.00000000e+00, 2.02492069e-01],
       [7.07000000e+02, 4.00000000e+00, 1.90538039e-01],
       [6.62000000e+02, 4.00000000e+00, 1.82177812e-01],
       [6.55000000e+02, 4.00000000e+00, 1.67267422e-01],
       [5.90000000e+02, 3.00000000e+00, 1.66664865e-01],
       [5.68000000e+02, 3.00000000e+00, 1.52328328e-01],
       [5.37000000e+02, 3.00000000e+00, 1.47862966e-01],
       [5.24000000e+02, 3.00000000e+00, 1.45450139e-01],
       [4.86000000e+02, 2.00000000e+00, 1.33847534e-01],
       [1.98000000e+02, 2.00000000e+00, 1.10662269e-01],
       [1.81000000e+02, 2.00000000e+00, 1.01108609e-01],
       [7.60000000e+01, 2.00000

In [138]:
corasimsort[:5]

array([[9.36000000e+02, 5.00000000e+00, 2.63998408e-01],
       [9.24000000e+02, 5.00000000e+00, 2.61483663e-01],
       [8.70000000e+02, 5.00000000e+00, 2.48860989e-01],
       [8.28000000e+02, 5.00000000e+00, 2.33142909e-01],
       [8.06000000e+02, 5.00000000e+00, 2.32259857e-01]])

In [127]:
corasimsort[:5,1]

array([0.26399841, 0.26148366, 0.24886099, 0.23314291, 0.23225986])

In [145]:
avg = np.average(corasimsort[:9,1])
abs(avg - df1t.rating[0])

0.33333333333333304

In [147]:
df1t.user[0]

1

In [148]:


coradf = df1b[df1b['item'] == df1t.item[0]]
cora = pd.DataFrame.to_numpy(coradf)

corasim = np.transpose(np.concatenate(([cora[:,0]],[cora[:,2]],[uu[df1t.user[0]-1,cora[:,0]-1]]),axis = 0))

corasimsort = np.sort(corasim,axis = 0)
corasimsort = corasimsort[::-1]

avg = np.average(corasimsort[:9,1])
abs(avg - df1t.rating[0])

0.33333333333333304